visualize_client:
  hdf5_open_file_path: /home/ericlab/tsuchida/2022_12/annotation/Semseg/t_pipe/sensor_b_box_3000_noize.hdf5

cloud_process:
  planar_threshold: 0.01
  x_min: -0.4
  y_min: -0.4
  z_min: -0.01
  x_max: 0.17
  y_max: 0.3
  z_max: 0.5
  

