visualize_client:
  hdf5_open_acc_service_name: hdf5_open_segmentation_service
  visualize_service_name: visualize_cloud_service
  hdf5_open_file_path: /home/ericlab/tsuchida/2023_01/annotation/Semseg/HV8/data_3000/3000_super_noize.hdf5

cloud_process:
  planar_threshold: 0.01
  x_min: -0.4
  y_min: -0.4
  z_min: -0.01
  x_max: 0.17
  y_max: 0.3
  z_max: 0.5
  

