common_parameter:
  LEAF_SIZE: 0.0015
  world_frame: base_link
  sensor_frame: photoneo_center_optical_frame
  util_msg_data:
    - instance: 0
      color:
        - 255
        - 255
        - 255
    - instance: 1
      color:
        - 255
        - 0
        - 0
    - instance: 2
      color:
        - 0
        - 0
        - 255
    - instance: 3
      color:
        - 255
        - 0
        - 0
    - instance: 4
      color:
        - 255
        - 255
        - 0
    - instance: 5
      color:
        - 0
        - 255
        - 255
    - instance: 6
      color:
        - 100
        - 0
        - 100
    - instance: 7
      color:
        - 100
        - 255
        - 0
    - instance: 8
      color:
        - 100
        - 100
        - 0
    - instance: 9
      color:
        - 255
        - 100
        - 0
    - instance: 10
      color:
        - 255
        - 100
        - 100
    - instance: 50
      color:
        - 255
        - 255
        - 255
    - instance: 300
      color:
        - 255
        - 255
        - 255