util_sensor:
  - instance: 0
    color:
      - 255
      - 255
      - 255
  - instance: 1
    color:
      - 0
      - 0
      - 255
  - instance: 2
    color:
      - 255
      - 255
      - 0
        
