hdf5_record_server:
  record_acc_service_name: record_acc_service
  record_segmentation_service_name: record_segmentation_service
  record_pose_estimation_service_name: record_pose_estimation_service
  record_clustering_service_name: record_clustering_service
  record_real_sensor_data_service_name: record_real_sensor_data_service
  hdf5_hdf5_record_service_name: hdf5_record_service
  record_hdf5_file_dir: /home/ericlab/tsuchida/2022_12/annotation/Semseg/multi_object_kai
  record_hdf5_file_name: kai.hdf5
  hdf5_save_interval: 100

