hdf5_open_server:
  hdf5_open_acc_service_name: hdf5_open_acc_service
  hdf5_open_sensor_data_service_name: hdf5_open_sensor_data_service
  hdf5_open_segmentation_service_name: hdf5_open_segmentation_service
 